---
- name: Install desktop pacman packages
  community.general.pacman:
    name: "{{ desktop_pacman }}"
  become: true

- name: Add user to desktop supplementary groups
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: "{{ desktop_user_groups }}"
    append: true
  when: not ansible_check_mode
  become: true

- name: Remove desktop pacman packages
  community.general.pacman:
    name: "{{ desktop_pacman_remove }}"
    state: absent
  become: true
