---
- name: Install desktop pacman packages
  community.general.pacman:
    name: "{{ desktop_pacman }}"
  become: true

- name: Install desktop AUR packages
  kewlfft.aur.aur:
    name: "{{ desktop_aur }}"
    use: paru
  become: false

- name: Add user to desktop supplementary groups
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: "{{ desktop_user_groups }}"
    append: true
  when: not ansible_check_mode
  become: true
