---

# Security packages

- name: Installing Security Packages
  pacman:
    state: latest
    name:
      - openvpn

- name: Installing Security Packages (AUR)
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - openvpn-update-systemd-resolved
