---
desktop_pacman:
  - 7zip
  - unrar
  - sof-firmware
  - cachyos-gaming-applications
  - ffmpeg
  - signal-desktop
  - moonlight-qt
  - spotify-launcher
  - zed
  - ghostty

desktop_aur:
  - google-chrome
  - wifiman-desktop
  - zoom
  - darkly

desktop_user_groups:
  - video

desktop_pacman_remove:
  - alacritty
  - cachyos-firefox-settings
  - cachyos-qtile-settings
  - firefox
  - firefox-i18n-en-us
  - firefox-pure
  - kde-utilities-meta
  - konsole
  - yakuake
