---
desktop_pacman:
  - 7zip
  - unrar
  - sof-firmware
  - cachyos-gaming-applications
  - ffmpeg
  - signal-desktop
  - moonlight-qt
  - spotify-launcher
  - zed
  - ghostty
  - wl-clipboard

desktop_aur:
  - google-chrome
  - wifiman-desktop
  - zoom
  - darkly
  - qrca

desktop_user_groups:
  - video

desktop_pacman_remove:
  - alacritty
  - firefox
  - konsole
