---

# Cleanup tasks that must be executed in any case (failure/success)

- name: Remove aur_builder
  user:
    name: aur_builder
    state: absent
    remove: yes

- name: Clean aur_builder permissions
  file:
    state: absent
    path: /etc/sudoers.d/11-install-aur_builder
