#!/bin/bash

RED='#FF0000' 
HEALTHY='#859900'
LOW='#b58900'

CAPACITY=`cat /sys/class/power_supply/BAT0/capacity`

if [ $CAPACITY <= 25 ]; then
    STATUS=$LOW
else
    STATUS=$HEALTHY
fi

echo " <span color=\"$RED\" font=\"20\">&#9829;</span> <span color=\"$STATUS\" font=\"20\" face=\"Courier New\">$CAPACITY%</span> "

