---

# Google Cloud SDK

- name: Checking Google Cloud SDK installation
  register: gcloud
  stat: path="/opt/gcloud/google-cloud-sdk"

- name: Download Google Cloud SDK installer
  when: gcloud.stat.exists == False
  get_url:
    url: https://sdk.cloud.google.com
    dest: /tmp/gcloud_installer.sh

- name: Install Google Cloud SDK
  when: gcloud.stat.exists == False
  shell: bash /tmp/gcloud_installer.sh --disable-prompts --install-dir=/opt/gcloud

- name: Clean temporary files
  when: gcloud.stat.exists == False
  file: path=/tmp/gcloud_installer.sh state=absent
