---
languages_python_pacman:
  - pyenv
  - uv

languages_rust_pacman:
  - rustup

languages_go_pacman:
  - go

languages_node_pacman:
  - fnm

languages_gopath: "{{ ansible_facts.env.HOME }}/.golang"
