---
- name: Install Go toolchain packages
  community.general.pacman:
    name: "{{ languages_go_pacman }}"
  become: true

- name: Create GOPATH directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ languages_gopath }}"
    - "{{ languages_gopath }}/bin"
  become: false
