---
- name: Configure Python
  ansible.builtin.import_tasks: python.yml

- name: Configure Rust
  ansible.builtin.import_tasks: rust.yml

- name: Configure Node.js
  ansible.builtin.import_tasks: node.yml

- name: Configure Go
  ansible.builtin.import_tasks: go.yml
