name: Nightly builds

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  arch-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Arch Linux container with Hanzo
        run: docker build . -t hanzo:test
              --build-arg HANZO_FULLNAME=test
              --build-arg HANZO_USERNAME=test
              --build-arg HANZO_EMAIL=test@example.com
