name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker container
        run: |
          docker build -f image/Dockerfile -t hanzo:test . \
            --build-arg HANZO_FULLNAME="Test User" \
            --build-arg HANZO_USERNAME=test \
            --build-arg HANZO_EMAIL=test@example.com
